// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAncY_9DaCuA6jVGLBj6GcWqhF72cVnYzE',
    appId: '1:738924952598:web:your-web-app-id',
    messagingSenderId: '738924952598',
    projectId: 'messenger-app-cf753',
    authDomain: 'messenger-app-cf753.firebaseapp.com',
    storageBucket: 'messenger-app-cf753.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAncY_9DaCuA6jVGLBj6GcWqhF72cVnYzE',
    appId: '1:738924952598:android:c397e9365d349b46b14937',
    messagingSenderId: '738924952598',
    projectId: 'messenger-app-cf753',
    storageBucket: 'messenger-app-cf753.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAncY_9DaCuA6jVGLBj6GcWqhF72cVnYzE',
    appId: '1:738924952598:ios:your-ios-app-id',
    messagingSenderId: '738924952598',
    projectId: 'messenger-app-cf753',
    iosBundleId: 'com.example.messenger_chat',
    storageBucket: 'messenger-app-cf753.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAncY_9DaCuA6jVGLBj6GcWqhF72cVnYzE',
    appId: '1:738924952598:ios:your-ios-app-id',
    messagingSenderId: '738924952598',
    projectId: 'messenger-app-cf753',
    iosBundleId: 'com.example.messenger_chat',
    storageBucket: 'messenger-app-cf753.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAncY_9DaCuA6jVGLBj6GcWqhF72cVnYzE',
    appId: '1:738924952598:web:your-web-app-id',
    messagingSenderId: '738924952598',
    projectId: 'messenger-app-cf753',
    authDomain: 'messenger-app-cf753.firebaseapp.com',
    storageBucket: 'messenger-app-cf753.firebasestorage.app',
  );
}
